---
title: Muhammad Althaf | Writer · Programmer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: althaf@muhammadalthaf.com
description: 'The Personal website of Muhammad Althaf - Writer, Programmer from India.

'
baseurl: ''
url: ''
twitter: http://twitter.com/althaffe
medium: http://medium.com/@althaffe
github: althaffe
google_analytics: 
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
sass:
  style: compressed
